### ISSUE TITLE
Can rust-mdo also simplify work with Zero-cost Futures?

### ISSUE THREAD

**Issue by vi** [TeXitoi/rust-mdo#3]
An example for [this article](https://aturon.github.io/blog/2016/08/11/futures/) asks for "do":

```
id_rpc(&my_server).and_then(|id| {
    get_row(id)
}).map(|row| {
    json::encode(row)
}).and_then(|encoded| {
    write_string(my_socket, encoded)
})
```

Can it be like

```
let q = fdo! {
    id <<= id_rcp(&my_server);
    row <<= get_row(id);
    let encoded = json::encode(row);
    write_string(encoded);
};
```

? Shall rust-mdo crate support `Future`s out of the box?

**Comment by TeXitoi** [comment]
Implementing a bind function for future should work. You can even do that outside for rust-mdo.

Implementing ret can be usefull, and implementing mzero is needed for the when syntax.

**Comment by TeXitoi** [comment]
rust-mdo will not support Future inside its repository to limit depedencies, but then bind/ret/mzero can be provided in another repository. If evolutions in rust-mdo can be useful for that, they will be included.

**Comment by vi** [comment]
What's wrong with having optional default-off dependency?

**Comment by TeXitoi** [comment]
what's wrong with 2 crates? ;-)

If crate A depend of rust-mdo, crate B of rust-mdo+future and crate C of A and B, you'll have 2 version of rust-mdo

If crate A depend of rust-mdo, crate B depend of rust-mdo and rust-mdo-future, and crate C of A and B, you'll have only one version of rust-mdo.

**Comment by TeXitoi** [comment]
If I have some time or need it, I'll write rust-mdo-future. Contributions welcome of course.

**Comment by TeXitoi** [comment]
Reading at the example, map must be handled.

**Comment by vi** [comment]
"must be handled" implies "can't be done from inside macro call"?

This `map` still looks like a boilerplate, so candidate for putting aside one way or another.

**Comment by TeXitoi** [comment]
If you want `let a = ...` transformed in `.map...`, you can't with the actual version of the macro.

And the macro expansion of mdo may not be appropriate to future, because it transforms in nested closure calls.

But you can do a syntax extension for future for sure.

**Comment by danslapman** [comment]
@vi @TeXitoi I just did it: https://github.com/danslapman/rust-mdo-future

**Comment by TeXitoi** [comment]
@danslapman great! I add a link to it in the README.md

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/rust-mdo/commit/49ac41cf4e53f9125857e1bd31d56cea99ea938f
